### ISSUE TITLE
Leadfoot get command hangs

### ISSUE THREAD

**Issue by JohnMealy23** [theintern/leadfoot#123]
First, awesome utility.  We're huge fans at my company.

We're having an issue where Leadfoot's `get` method never resolves.  We're fairly certain this is due to the client-side code never registering that the page has fully loaded.  This may be due to a large (and necessary) amount of scripts loading on the page.  

Assuming this is the case, a docReady override time would be a great second argument to the `get` method.

**Comment by jason0x43** [comment]
Leadfoot has a `setPageLoadTimeout` method ([v1](https://theintern.io/leadfoot/module-leadfoot_Command.html#setPageLoadTimeout), [v2](https://theintern.io/docs.html#Leadfoot/2/api/Command/setpageloadtimeout)) that sounds like it does what you're looking for.

**Comment by jason0x43** [comment]
That would cause the get to fail, but you could catch the timeout and proceed if that was the intention.

**Comment by jason0x43** [comment]
Any updates for this issue?

**Comment by jason0x43** [comment]
Closing since there hasn't been anything new in a while.
