### ISSUE TITLE
Add more detailed `pressKeys` docs

### ISSUE THREAD

**Issue by jason0x43** [theintern/leadfoot#129]
Add an example or two. Show how to use `keys`.

**Comment by ajc24** [comment]
Are there any further updates as to how this issue is coming along?

I'm trying to get a working example of how to use the `pressKeys()` method in Intern 4 and am finding it virtually impossible. My own attempts at the method have yielded no luck - I have no idea if I'm doing something incorrectly due to the lack of docs unfortunately.

**Comment by jason0x43** [comment]
Sorry, this keeps getting overridden by other things.

You can import keys with `import keys from '@theintern/leadfoot/keys';`, then just use [the constants](https://theintern.io/docs.html#Leadfoot/2/api/keys) with `pressKeys`, like:

```js
pressKeys(keys.RETURN)
```

**Comment by ajc24** [comment]
Thank you :) The only issue I have is that I'm restriced in that it will now allow imports to be done in that manner (ie. using the `import` keyword).

Our workspace has followed the examples and used:
```
const { assert } = intern.getPlugin('chai');
const { registerSuite } = intern.getInterface('object');
``` 

Is there another way to import that module without using the `import` keyword, similar in format to what is in place already?

**Comment by jason0x43** [comment]
```js
var keys = require('@theintern/leadfoot/keys').default;
```

Note that we're using the `default` property; that necessary since the library is using an ES6 default export.

**Comment by ajc24** [comment]
Perfect thank you!

**Comment by jason0x43** [comment]
Closing this as resolved for now. All the docs will be updated for the next major release.
