### ISSUE TITLE
Leadfoot throws TypeError when trying to launch new FF 58 with GeckoDriver 19.1

### ISSUE THREAD

**Issue by silne30** [theintern/leadfoot#139]
Environment:

Mac OSX 10.3.3
Node.js - 6.12.2
Leadfoot: 1.7.4  - 2.0.0 beta 8
Browser: Firefox 58
GeckoDriver: 19.1

1.) Use leadfoot directly to start browser
2.) Use standard capabilities

Expected Result:
Browser starts with capabilities

Actual Result: 
Browser fails to start with stack trace:

RROR  TypeError: Cannot read property 'platform' of undefined
           at Server._fillCapabilities (/Users/silne30/Desktop/kibana/node_modules/leadfoot/Server.js:395:19)
           at /Users/silne30/Desktop/kibana/test/functional/services/remote/leadfoot_command.js:33:18
           at undefined.next (native)
           at step (/Users/silne30/Desktop/kibana/test/functional/services/remote/leadfoot_command.js:104:191)
           at /Users/silne30/Desktop/kibana/test/functional/services/remote/leadfoot_command.js:104:361
           at process._tickDomainCallback (internal/process/next_tick.js:135:7)

**Comment by jason0x43** [comment]
Could you post your intern config (at least the environments section)?

**Comment by silne30** [comment]
We are not using intern at all. We are using leadfoot directly and implementing the start() stop functions.

I found the issue though and will contribute the fix.

**Comment by silne30** [comment]
/CC @jason0x43 I submitted #140 to fix this. Unfortunately, I can't edit the reviewers section to request a review.

I committed the change against 1.7 since that is the version we are using but the change is simple enough to be ported across the board once it's verified to work.

**Comment by jason0x43** [comment]
This was resolved by #141 and is included in 1.7.5.
