### ISSUE TITLE
Feature detection test: Firefox access restrictions on objects passed from the client

### ISSUE THREAD

**Issue by csnover** [theintern/leadfoot#14]
FirefoxDriver creates objects through some XPCOM interface that throws “Permission denied to access property <property>” if you do something like this:

```js
session.execute(function (obj) {
// Error: Permission denied to access property "count"
++obj.count;
return obj;
}, [ { count: 0 } ]);
```

This is different from other browsers that do not have a problem with mutating passed objects, so there should be a detection test for it.

**Comment by jason0x43** [comment]
Closing this since we've moved on to geckodriver
