### ISSUE TITLE
"POST /execute" breaks on updated drivers when using Leadfoot directly.

### ISSUE THREAD

**Issue by cuff-links** [theintern/leadfoot#143]
When using Leadfoot by itself, GeckoDriver > 16.0 breaks when using the "POST /execute" function.

The webdriver spec has updated this to be "POST /execute/sync" and [GeckoDriver](https://github.com/mozilla/geckodriver/releases) updated that a few versions ago. I wanted to get your thoughts on how to handle and I will post a fix.

Should we: 
1.) Create a conditional to check the version of the driver edit the endpoint so as not to break drivers that haven't updated their spec yet (i.e. Chromedriver).
2.) Something else I haven't thought of.

**Comment by silne30** [comment]
When using "POST /execute", the command fails with a "Command not found error." I monkey-patched my local fork just to check if the "POST /execute/sync" endpoint works, and it does.

My environment: Mac OSX
Geckodriver: 20.0
Firefox: 59
LeadFoot: 1.7.5

**Comment by jason0x43** [comment]
There's not a way (that I'm aware of) to query the webdriver about its own version, so we'll probably need to handle it via a custom feature and a fallback behavior in the `execute` function, something like `Session.closeCurrentWindow`.

Basically, if leadfoot tries to call `/execute` and gets back an `UnknownCommand` message, it should assume the driver is using newer semantics, set a `useWebDriverExecute` flag (so we'll know not to use the wrong command again), and call `/execute/sync` instead.

**Comment by silne30** [comment]
Sounds good. I will get on it.

**Comment by silne30** [comment]
Can you assign to me? Or is that not possible?

**Comment by cuff-links** [comment]
This has been fixed via the referenced PRs/
