### ISSUE TITLE
session.clearCookies() on Edge results in TypeError: Cannot read property 'map' of null

### ISSUE THREAD

**Issue by SanderDeWaal1992** [theintern/leadfoot#149]
This code:
`await session.clearCookies();`
Results in this error:
```
TypeError: Cannot read property 'map' of null
      at C:\...\src\Session.ts:938:19
      at C:\...\node_modules\@dojo\core\0.5.0\async\Task.ts:351:13
      at handler (C:\...\node_modules\@dojo\core\0.5.0\async\ExtensiblePromise.ts:229:15)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:160:7)
```

Using :
- Leadfoot 2.1.0
- Microsoft Edge 42.17134.1.0
- docker-selenium 3.12.0

**Comment by gitgrimbo** [comment]
FYI - https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/14838528/.

I can reproduce this. When using Edge driver, `getCookies()` can return `null` if there are no cookies, and a subsequent call to `cookies.map()` fails as `cookies===null`.

**Comment by jason0x43** [comment]
A feature flag was added to handle this in 24f59448 (some time ago), but it's probably moot at this point since Chromium Edge is a thing. 😄
