### ISSUE TITLE
@types/node observable declaration conflicts with leadfoot

### ISSUE THREAD

**Issue by SanderDeWaal1992** [theintern/leadfoot#151]
**Expected behavior**

I can build my project with TypeScript

**Current behavior**

Error All declarations of 'observable' must have identical modifiers. happens when compiling TypeScript tests.

This is because @dojo/shim (version 0.2.7) declares observable: symbol; while @types/node declare readonly observable symbol;.

Those declarations conflict and TSC won't build.

**Full log:**

```
 C:/Source/**/@dojo/shim/Symbol.d.ts(3,9): error TS2687: All declarations of 'observable' must have identical modifiers.
C:/Source/**/@types/node/index.d.ts(169,14): error TS2687: All declarations of 'observable' must have identical modifiers.
```
**Possible solution**

Updating to a version that doesn't conflict, or replacing it by something else?
Steps to reproduce (for bugs)

    Add Leadfoot to npm package.
    Also have a recent @types/node dependency (ie. 10.5.1)
    Try to build with TypeScript 

**Environment**

Leadfoot version: 2.1.0
Node version: 10.5.0
NPM version: irrelevant
Browser version: irrelevant

**Comment by jason0x43** [comment]
This is related to https://github.com/theintern/intern/issues/932 and https://github.com/dojo/shim/issues/144.

**Comment by jason0x43** [comment]
Since we dropped dojo/shim some time ago, this is no longer an issue.
