### ISSUE TITLE
clearCookies() does not seem to work with Edge driver 17134

### ISSUE THREAD

**Issue by gitgrimbo** [theintern/leadfoot#152]
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/14838528/#comment-7

Perhaps `this.capabilities.brokenDeleteCookie` needs to include "Edge driver 17134".

https://github.com/theintern/leadfoot/blob/0978a55a3a68005aa998346410eb66a7f797dbca/src/Session.ts#L1023..L1053

**Comment by gitgrimbo** [comment]
Also see #163 for whether the Edge workarounds for cookie handling are required any more.

**Comment by jason0x43** [comment]
Edge's cookie handling was updated in Leadfoot 2.2.11. The feature test was enabled for Edge 18+ (44.17763+), and delete support was marked as broken for Edge < 18 (the feature test passed in at least one case where deletion didn't actually work during the self tests).
