### ISSUE TITLE
Please re-export dojo Task from leadfoot typings

### ISSUE THREAD

**Issue by rogierschouten** [theintern/leadfoot#158]
Recently, leadfoot started depending on a new version of Dojo. This broke our build. This is because leadfoot functions, such as Server#createSession(), return a dojo Task, but the Task is not exported from the leadfoot typings. That means that for us to declare a variable of the Task type, we have to manually import Task from dojo/core. And therefore we also need to explicitly depend on dojo/core; and the versions no longer matched. 

Please re-export the Task from leadfoot, i.e. put something like this in your index.ts file:

```typescript
import { Task } from "@dojo/core";
export { Task };
```

**Comment by jason0x43** [comment]
Is there a reason that you need to create a Task rather than a Promise or a Command? (Just confirming the use case.)

**Comment by rogierschouten** [comment]
@jason0x43 I'll have to look that one up next week (it was code from a colleague).  In any case, what's returned by the functions should also be re-exported. So if there is no use case for Task, then the functions should also not return Tasks but rather Command/Promise

**Comment by jason0x43** [comment]
Oh, I see the issue. It sounds like you want to declare a Task variable to hold something returned by Leadfoot. I was thinking you wanted to create new Task instances, which external code shouldn't do (the Task class may change or go away at some point, so it'd be best not to have that sort of direct dependency).

I'll export a Task or CancellablePromise interface.

**Comment by jason0x43** [comment]
Resolved in ff4331a, released in 2.2.0
