### ISSUE TITLE
Appium does not return webview for url open in InAppBrowser of cordova app

### ISSUE THREAD

**Issue by Sumanjit13** [theintern/leadfoot#160]
We have app which is based on the OpenPos framework and JumpMind is the owner. POS app opens a window within the context of the Point of Sale application which displays web content. Appium command driver.getContextHandles() returns only one webview and not webview for window shows web content.
Driver.getWindowHandles() also return only one window and that also didn't work.

I can see two webviews in Safari-> Develop -> Device when second window opens inside cordova app.

We are blocked here and to work on web elements of second window appium need to switch to webview of that window. Please help

Appium version : 1.9.1

**Comment by jason0x43** [comment]
Closing this as not related to Leadfoot
