### ISSUE TITLE
Why does switchToFrame bother checking `usesWebDriverFrameId` if it sends an Element ref anyway?

### ISSUE THREAD

**Issue by gitgrimbo** [theintern/leadfoot#162]
https://github.com/theintern/leadfoot/blob/a8fbfe7ffc3e7efdb85c7f31a8a3204085ae9ad9/src/Session.ts#L501..L508

```js
  switchToFrame(id: string | number | Element | null) {
    if (this.capabilities.usesWebDriverFrameId && typeof id === 'string') {
      return this.findById(id).then(element =>
        this.serverPost<void>('frame', { id: element })
      );
    }
    return this.serverPost<void>('frame', { id: id });
  }
```

If leadfoot is automatically converting DOM element ids into DOM element references, then why do we need to check compatibility?

Wouldn't we only need to check `this.capabilities.usesWebDriverFrameId` if we were sending id strings to the web driver impl directly?

It looks like we can drop the capability check completely if we're doing the `id string -> DOM element` conversion in leadfoot.

**Comment by jason0x43** [comment]
[W3C WebDriver](https://www.w3.org/TR/webdriver/#switch-to-frame) requires the `id` to be a number or an object representing a web element, while [JsonWireProtocol](https://github.com/SeleniumHQ/selenium/wiki/JsonWireProtocol#sessionsessionidframe) will work with a string `id`. If the remote uses W3C style frame IDs and `switchToFrame` is called with a string ID, Leadfoot needs to convert that ID to an element object. If, however, the endpoint doesn't use W3C-style frame IDs, then it will work with a string and there's no point in doing a conversion.

There is no implicit conversion of DOM element IDs to element references here. If `switchToFrame` were called with a string and the conversion code wasn't there, then the string ID would be passed directly to the remote via the `serverPost` call.

**Comment by maxbeatty** [comment]
What you're describing with a string ID being passed directly to the remote seems to be what's happening in #186 🤔
