### ISSUE TITLE
Can't perform a right click with clickMouseButton(2)

### ISSUE THREAD

**Issue by jake-harrington** [theintern/leadfoot#180]
Description: Chromedriver 75+ doesn't right click with clickMouseButton(2). I'm seeing the same thing happening in IE11 (IE driver 3.14, Selenium 3.141.59).

Steps to reproduce:

Run the sample linked at the end, but it otherwise does:
```
    return this.remote
        .get(require.toUrl('http://localhost:7357/test.html'))
        .findByCssSelector('#test-input')
        .moveMouseTo()
        .clickMouseButton(2)
        .end()
        .sleep(10000)
```

Expected result: A context menu should open
Actual result: A regular click is performed on the field

Intern version: 4.4.3

Any additional information:
@jason0x43 on Gitter:
"Hmm...it looks like they switched to W3C standard compliant mode by default in chromedriver 75, which will affect how arbitrary mouse events works because strict W3C webdriver doesn't support the session-level mouse endpoints Intern is currently using."

I'm using Selenium 3.14.
Here's an example project exhibiting the behavior (`npm run server` to start, then `npm test`). It should open a context menu on a text input.
[intern-test.zip](https://github.com/theintern/leadfoot/files/3392651/intern-test.zip)

**Comment by jason0x43** [comment]
Closing this in favor of theintern/intern#1036
