### ISSUE TITLE
Provide a `waitForVisible()` method

### ISSUE THREAD

**Issue by darkwing** [theintern/leadfoot#23]
I've been doing a lot of functional testing where I'm:

(1)  Waiting for an element to fade in, or
(2)  Waiting for a page to turn or reload, then grab an element

LF's `pollUntil` is a nice helper but the use case for a method which accomplishes both of the items above would be super helpful.  `pollUntil` also appears to require a DOM/JS test but I'd prefer to use LF's `isDisplayed` for testing visibility and presence.  Now I'm using the following custom function:

```
...
pollForRemote: function(item, remoteFunction, callback, timeout) {
            // Allows us to poll for a remote.{whatever}() method async result
            // Useful when waiting for an element to fade in, a URL to change, etc.

            // Defaults for arguments not passed
            timeout = timeout || config.testTimeout;
            callback = callback || function(result) {
                return result === true;
            };

            var dfd = new Deferred();
            var endTime = Number(new Date()) + timeout;

            (function poll() {
                item[remoteFunction]().then(function() {

                    if(callback.apply(this, arguments)) {
                        dfd.resolve();
                    }
                    else if (Number(new Date()) < endTime) {
                        setTimeout(poll, 100);
                    }
                    else {
                        dfd.reject(new Error('timed out for ' + remoteFunction + ': ' + arguments));
                    }
                });
            })();

            return dfd.promise;
        },
...

// Usage
utils.pollForRemote(element, 'isDisplayed').then(function() { /* ... */ });
```

`pollUntil` and `setFindTimout`/`find` methods seem to be most of the way there but a combination of the two would be incredibly helpful.

Hopefully my request is somewhat clear, I'd be happy to speak about it further.

**Comment by cloudbring** [comment]
I'm implimenting tests and this would be very useful.

I am currently trying to script a link that opens a new window. A general `waitUntil` that takes a function (and passes in the context) and loops until that function returns true or timeout would be super helpful.

**Comment by albertogasparin** [comment]
+1 :+1:

**Comment by bartoszkaczorek** [comment]
+1

**Comment by csnover** [comment]
Thanks guys for your interest! We’re accepting patches for this feature if you want to see it sooner rather than later, so your help would be appreciated! Committers are standing by to provide assistance in IRC (#intern on Freenode) if you want to write a patch.

**Comment by juanpicado** [comment]
Can you merge this change in a posible future version of Intern 2.2.3 ? I really need this in my tests.
