### ISSUE TITLE
Allow for global configuration of "setFindTimeout"

### ISSUE THREAD

**Issue by vladikoff** [theintern/leadfoot#3]
To assist with JavaScript template page rendering, help keep the tests short and DRY, there should be a way to configure the default [setFindTimeout](http://theintern.github.io/leadfoot/Session.html#setFindTimeout) in Leadfoot via Intern.
The test may override the default value by calling `setFindTimeout()`.

intern.js

```
leadfoot: {
findTimeout: 10000
},
```

### Before
【 code  】
'load a dynamic view page': function () {
 return this.get('remote')
 .get(require.toUrl(url))
 .setFindTimeout(intern.config.pageLoadTimeout)
 .findByCssSelector('.funnyCssSelector')
 .click()
 .end()
【 end code 】

### After
【 code  】
'load a dynamic view page': function () {
 return this.get('remote')
 .get(require.toUrl(url))
 .findByCssSelector('.funnyCssSelector')
 .click()
 .end()
【 end code 】

cc @zaach

**Comment by sholladay** [comment]
+1 for this and making the configuration hierarchical.

**Comment by csnover** [comment]
@sholladay We’d love to do this, but we don’t have enough manpower to implement this feature as quickly as you’d probably like to see it. If you would like to work on implementing please stop in on the IRC channel during the week (#intern on Freenode) and someone can help you out. We’d love to get your help. Thanks!

**Comment by httpete** [comment]
+1, I am doing setFindTimeout on every test.. And it tends to interfere with adoption as that is the first thing I hit on two projects.

**Comment by jason0x43** [comment]
This was resolved quite some time ago -- https://theintern.io/docs.html#Intern/4/api/lib%2Fcommon%2Fconfig/functionaltimeouts
