### ISSUE TITLE
Intern tests timeout after 30s

### ISSUE THREAD

**Issue by mgingras** [theintern/leadfoot#30]
Tests timeout after 30s due to the implicit timeout in the intern Test object. This is not apparently accessible from Leadfoot's api or clearly documented. In functional testing it is quite plausible to have to wait 30s, imagine waiting for a large graphic to render or large AJAX request.

It can be overwritten on within a test itself as follows:

```js
 this.timeout = x;
```

However that isn't documented from what I can tell and gets tedious if you have dozens of tests you don't want to fail with an implicit timeout. As a workaround you can write a parent suite of your own which all your Tests inherit from and overwrite the test object there. I.e.

```js
define([
	'intern!object',
	'intern/lib/Test'
], function (registerSuite, Test) {
  Test.prototype.timeout = 60000; // Where this is the max timeout you're willing to have for a single test
  return function(suite){
    registerSuite(suite)
  };
}
```

Then have every test register through this suite.

**Comment by csnover** [comment]
I believe there is already a request open for this at https://github.com/theintern/intern/issues/350 so I will close this but please let me know if this is actually a separate issue and I will reopen. Thanks!
