### ISSUE TITLE
Add support for 'findByElement'

### ISSUE THREAD

**Issue by necolas** [theintern/leadfoot#31]
Similar to the other find commands but the input is a `leadfoot/Element`.

Webdriver interface: http://selenium.googlecode.com/git/docs/api/java/org/openqa/selenium/WebDriver.html#findElement(org.openqa.selenium.By)

**Comment by csnover** [comment]
Sorry, I am confused…if you already have the element, why would you try to find it?

**Comment by necolas** [comment]
I was using an element as context passed to a "page object", but no longer use this pattern. And you're right, it's a bit circular as a request :).
