### ISSUE TITLE
Favicon missing on https://theintern.github.io/leadfoot/

### ISSUE THREAD

**Issue by johntrandall** [theintern/leadfoot#34]
the helmet logo is wonderful. 
It should be shown when I pin my tab. It needs a favicon.

**Comment by csnover** [comment]
The site is open-source in the gh-pages branch so send a PR for a favicon if you’d like to see one! Thanks!

**Comment by csnover** [comment]
Per the comment on the PR please feel free to add favicon support to the theme. I’m going to close this ticket since it’s trivial and nobody on the project is going likely to ever actually work on this, but we’re still happy to accept a patch if you want to send it.
