### ISSUE TITLE
List of driver fixes?

### ISSUE THREAD

**Issue by geekdave** [theintern/leadfoot#36]
Hello,

I'm intrigued by:

```
Leadfoot currently detects and corrects known defects in the following remote drivers:
```

and I'm wondering if there is a list somewhere of what these fixes are.  

I'm also curious if there's been any luck actually getting browser vendors to fix any of the issues you've reported?

Thanks!

**Comment by csnover** [comment]
> I'm wondering if there is a list somewhere of what these fixes are. 

https://theintern.github.io/leadfoot/global.html#Capabilities

> I'm also curious if there's been any luck actually getting browser vendors to fix any of the issues you've reported?

Pretty much not. I think the teams responsible for all this software are super underfunded (present company included).
