### ISSUE TITLE
Usage as stand-alone webdriver?

### ISSUE THREAD

**Issue by geekdave** [theintern/leadfoot#37]
> Leadfoot can be installed and used as a stand-alone WebDriver library from npm 

I'm curious if this integration is possible with libraries like admc/wd and nightwatch?  How would leadfoot be injected "in between" the test-runner library and the "real" webdriver?  

Any simple examples would be much appreciated!

**Comment by csnover** [comment]
You can try, but it’s not supported. Leadfoot is a replacement for WD.js, which we used to use and got rid of because the code quality was very bad. Nightwatch doesn’t do everything Intern does so if you are trying to use Nightwatch you should just use Intern instead. :)
