### ISSUE TITLE
Unable to switch to newly created window

### ISSUE THREAD

**Issue by cezarykluczynski** [theintern/leadfoot#39]
Hi.

I'm trying to write a piece of code that will open a page that opens a window through window.open().

Then I need to switch to that other window and do some assertions there.

However, I'm hitting the wall since it seems unpossible to do so, because the following code throws an error:

```javascript
define([
	"intern!object",
	"intern/chai!assert"
], function ( registerSuite, assert ) {
	var windowHandles, mainWindowHandle;

	registerSuite({
		name: "Test",

		"Test window switching.": function () {
			return this.remote
				.get( "http://google.com/" )
				.getCurrentWindowHandle()
				.then( function ( currentHandle ) {
					mainWindowHandle = currentHandle;
				})
				.execute( function () {
					window.open( "http://google.com/", "", "width=200, height=200" );

					return true;
				})
				.end()
				.getAllWindowHandles()
				.then( function( handles ) {
					windowHandles = handles;
				})
				.switchToWindow( windowHandles[ 1 ] )
				.getCurrentWindowHandle()
				.then( function ( currentHandle ) {
					assert.notEqual( currentHandle, mainWindowHandle );
					assert.equal( currentHandle, windowHandles[ 1 ] );
				});
		}
	});
});
```

Error is:

    TypeError: Cannot read property '1' of undefined
      at Test.registerSuite.Test window switching. [as test]  <tests\functional\test.js:27:35>

So switchToWindow() function is to blame, and the reason is, I think, that it only accept strings.

However, if it was to accepts functions too:

```javascript
	switchToWindow: function (name) {
		return this._post('window', {
			name: typeof name === "function" ? name() : name
		}).then(noop);
	},
```

then the problem is fixed with the following code, and then the test passes:

```javascript
				.switchToWindow( function () {
					return windowHandles[ 1 ];
				})
```

I'm not sure I'm approaching the problem right. Is there a better solution to get a window handle, then to switch to that window? Or ss the pull request with a patch to switchToWindow, so it will accept both strings and functions, an acceptable solution?

**Comment by vladikoff** [comment]
Hm, just at a glance, this seems really complex.

Try something like this, pseudo code
```
.execute(function ) {
            var newWindow = window.open(url, 'somename');
          }, e ]);
.switchToWindow('somename')
// context is now the opened window
```
then you can use
```
 .closeCurrentWindow()
 .switchToWindow('') // goes back to original window
```

See example here: https://github.com/mozilla/fxa-content-server/blob/849292a04aecf85d2abf4ddf8b36dabc24000534/tests/functional/delete_account.js#L153

**Comment by cezarykluczynski** [comment]
Thank you! I Your solution solved my problem.
