### ISSUE TITLE
.moveMouseTo() causes a client-side exception in some cases

### ISSUE THREAD

**Issue by sholladay** [theintern/leadfoot#40]
With some test designs, I get errors like this:
````bash
UnknownError: [POST http://127.0.0.1:4447/wd/hub/session/abd45f0d-9053-44f7-8cad-8a0f321f88b4/moveto / {"element":"11","xoffset":1,"yoffset":1}] unknown error: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
````

Minimal failing test case in Intern:

````javascript
define(['intern!tdd'], function (tdd) {
    tdd.suite('foo', function () {
        tdd.test('bar.', function () {
            return this.remote.moveMouseTo(1, 1)
        });
    });
});
````

If I add something like `.findByCssSelector('p')` right before the .moveMouseTo() call, then everything is fine. Also, if I've moved the mouse previously via an element, then everything is fine. It seems to be a combination of the *element-less* call signature I'm using and the fact that it's the first time.

My expectation is that the `Element` argument is always optional and that it should take care of first-time vs not quirks.

*Environment*:
**Intern:** `2.2.2`
**Leadfoot:** `1.2.1`
**Chrome:** `43.0.2357.65`
**ChromeDriver:** `2.9.248307`
**OS:** `OS X 10.10.3`

**Comment by csnover** [comment]
This is an upstream bug introduced in Chrome 41. https://code.google.com/p/chromedriver/issues/detail?id=1049

**Comment by csnover** [comment]
Team Chrome doesn’t seem to care, so another feature detect & workaround has been added in 1.6.1 for this.
