### ISSUE TITLE
Command + v for pasting contents from clipboard does not work

### ISSUE THREAD

**Issue by arvindh5686** [theintern/leadfoot#42]
I have contents in the clipboard which I would like to paste to a textbox.
When I try 

.click()
.pressKeys(['\uE03D', 'v'])

it does not paste the contents to the textbox. All other special keys work. For example, for using shift key, when I do 

.pressKeys(['\uE008', 'v', '\uE000'])

 it prints 'V' as expected.

Any advice on this would be highly appreciated.

**Comment by csnover** [comment]
What OS are you using? e03d is not the correct key for Windows or Linux.

**Comment by arvindh5686** [comment]
I am using a Mac OS Yosemite

**Comment by gabhi** [comment]
+1 what is the code to send paste command?

**Comment by mbhatti03** [comment]
Can you please provide the code to paste the values from excel to UI?

**Comment by mbhatti03** [comment]
Please can anyone respond to this question?

**Comment by csnover** [comment]
This is an upstream bug https://code.google.com/p/selenium/issues/detail?id=8555

**Comment by csnover** [comment]
Unfortunately there is nothing that can be done to fix this from the client (i.e. Leadfoot) since the problem is that the server isn’t accepting the normal keyboard commands for copy/paste on that OS.
