### ISSUE TITLE
ChromeDriver running tests before they should

### ISSUE THREAD

**Issue by darkwing** [theintern/leadfoot#46]
I have a helper function which confirms that a given window property exists:

```
function windowPropertyExists(remote, property) {
    // Ensures a window[key] property exists in the page
    // Missing global properties could be a sign of a huge problem
    return remote.execute('return typeof window.' + property + ' != "undefined"').then(function(result) {
        assert.isTrue(result, 'The following window property exists:  ' + property);
    });
}

// Simple usage: Ensure jQuery loads properly (sync load in the webpage)
var remote = this.remote;
return remote.get('/')
                        .then(function() {
                            return libAssert.windowPropertyExists(remote, 'jQuery');
                        })
```

While Firefox always reports true, Chrome is hit or miss, despite the code never changing.  It seems as though the Chrome tests are being run before the page has downloaded resources, even when those SCRIPTs (for example) are loaded sync.

If I add a `sleep(5000)` after the `get`, the test always passes, but since the jQuery file is being loaded sync, that property should be there and the test should pass.

Since tests always pass in Firefox and a `sleep` allows the test to return true, I can only conclude that tests are being run by ChromeDriver *before* the page load is complete.

**Comment by vladikoff** [comment]
@darkwing you are assuming that `return remote.get('/')` waits for "page loaded" or DOMContentLoaded. I don't think that is the case. It will probably work properly with https://theintern.github.io/leadfoot/pollUntil.html which will poll until window.jQuery is not undefined for instance

**Comment by darkwing** [comment]
We can use polling, of course, but it seems logical (or probably just "hopeful") that leadfoot (...and maybe Selenium) can standardize/sync the test kickoff for when the page has completed load.

Maybe this is a hopeful enhancement?

**Comment by vladikoff** [comment]
> We can use polling, of course, but it seems logical (or probably just "hopeful") that leadfoot (...and maybe Selenium) can standardize/sync the test kickoff for when the page has completed load.

It is complex. What is considered "loaded"? if my app has a javascript dialog that shows up after 5 seconds should Selenium somehow guess that window.mySlowDialog will exist?

I think Selenium already has some "loaded" state for the HTML document, which I think means if you query for `<html>` then you would always find it. Even then I would personally not trust it and would poll for the element instead.

**Comment by darkwing** [comment]
I guess I can accept that.  Thanks for the different insight.
