### ISSUE TITLE
Request Headers

### ISSUE THREAD

**Issue by tkaufman** [theintern/leadfoot#49]
Would be great to be able to set a request header like Accept-Language in order to test some of the other more challenging parts of our application. I can't seem to find a way to do that via theintern or leadfoot however.

**Comment by csnover** [comment]
I’m sorry, I don’t fully understand this request. You want to set request headers where? Leadfoot just tells a browser to do things and then browser does it the same way it would do if an actual user were interacting with it.

**Comment by tkaufman** [comment]
Here? https://github.com/theintern/leadfoot/blob/master/Server.js#L45

**Comment by csnover** [comment]
I’m sorry, I still don’t understand. What would that help you test? That’s for communication between the WebDriver client and WebDriver server. It doesn’t have anything to do with your applications.

**Comment by jason0x43** [comment]
Neither Selenium nor the genera WebDriver protocol provide any method for setting custom headers on browser requests. The easiest thing to do at the moment is probably to route browser requests through a proxy that can add the headers.

**Comment by csnover** [comment]
Closing due to lack of response from OP. If you are able to provide the requested information I will reopen the ticket. Thanks!
