### ISSUE TITLE
Leadfoot is not adding "Accept" header when redirecting requests

### ISSUE THREAD

**Issue by bartoszkaczorek** [theintern/leadfoot#54]
### Overview

Leadfoot is not adding *Accept* header when redirecting requests. This happened when trying to initialize firefox session using selenium grid on Linux. 

The comment below (found in Server.js) says additional header needs to be added when creating session and it seems that this is the case here, but the header is not added when the request redirection occurs:
```javascript
headers: {
	// At least FirefoxDriver on Selenium 2.40.0 will throw a NullPointerException 
	// when retrieving session capabilities if an Accept header is not provided.
	// (It is a good idea to provide one anyway)
	'Accept': 'application/json,text/plain;q=0.9'
},
```
			
I had to add below code to Server.js (line ~70) so that required header is added when request redirection occrus which seems to fix my issue:
```javascript
// The JsonWireProtocol specification prior to June 2013 stated that 
// creating a new session should perform a 3xx redirect to the
// session capabilities URL, instead of simply  returning the returning
// data about the session; as a result, we need to follow 
// all redirects to get consistent data
if (response.statusCode >= 300 && response.statusCode < 400 && response.getHeader('Location')) {
	return request(response.getHeader('Location'), {
		headers: {
			'Accept': 'application/json,text/plain;q=0.9'
		},
		method: 'GET'
	}).then(handleResponse, handleResponse);
}
```

### Environment details

Intern: 3.0.0
Selenium hub version: 2.31
Platform: Linux
Browser: Firefox

**Comment by csnover** [comment]
Thanks for the information. Leadfoot isn’t validated to work with a Selenium version prior to 2.41.0, so while I can certainly try to look into this I know there are a variety of defects in older Seleniums such that this probably won’t be the last one you run into, so just upgrading might be a better solution for you. Please let me know your thoughts.

**Comment by bartoszkaczorek** [comment]
I agree updating Selenium is be the best solution and probably we will do that soon, but it would be nice if intern could support it.
