### ISSUE TITLE
no method to select a value in a selection list

### ISSUE THREAD

**Issue by LeeDr** [theintern/leadfoot#56]
I don't see any method here https://theintern.github.io/leadfoot/Element.html to select a value in a select list.  I tried click() on the select object followed by a click() on the option value.  That highlights the value but doesn't really select it.
A developer for our product helped me out with this work-around.
```javascript
remote.execute('$(arguments[0]).val(arguments[1]).change()', [timefield, myvalue])
```
Is there a supported way for selection lists and I just don't see it? We should have something like the WebDriver 'selectByVisibleText' method.

**Comment by csnover** [comment]
`click` is the right method and there is actually even a test case that does exactly this at https://github.com/theintern/leadfoot/blob/master/tests/functional/Element.js#L436-L461 so it sounds like maybe a Selenium driver has broken or you have some focus issue on the test machine. Can you please provide more information and a test case?

**Comment by LeeDr** [comment]
Thanks for the fast response.  I'm looking at the test case you referenced.  I'll try on my side again and I'll use isSelected() to see what it says after I click() on the value element.  I'll come back on this soon...

**Comment by LeeDr** [comment]
I confirmed that it works like your test.  Not sure what I had wrong initially.  Nothing to see here.
Thanks @csnover !
