### ISSUE TITLE
DragAndDrop seems not working.

### ISSUE THREAD

**Issue by brunano21** [theintern/leadfoot#64]
Hi,
I'm playing a bit the drag and drop functionalities, and I'm using the leadfoot's helper, DragAndDrop.
I have the following code as shown into the example. It runs against my web app (which uses dojo widgets and [dojo dnd ](http://livedocs.dojotoolkit.org/dojo/dnd)), for both Chrome and Firefox.

    return new DragAndDrop(remote)
        .findByXpath(source)
        .dragFrom()
        .end()
        .findByXpath(target)
        .dragTo()

I have the return statement because this code is part of a promise chain. However, I do not get any kind of errors|exceptions, neither in the browser neither in selenium neither on intern  side. Honestly, I have no idea where to start from.
Any suggestion? May I provide further information?

**Comment by brunano21** [comment]
I solved using the code found here:
https://github.com/jason0x43/dojo/blob/intern-dnd/tests-intern/functional/dnd.js

    .findByXpath(source)
    .click()
    .moveMouseTo()
    .pressMouseButton(1)
    .sleep(200)
    .end()
    .moveMouseTo(10, -10)
    .sleep(200)
    .findByXpath(target)
    .moveMouseTo()
    .sleep(200)
    .releaseMouseButton()
    .end();

Thanks @jason0x43 :)

**Comment by csnover** [comment]
There is no drag and drop in Leadfoot so I don’t know what this ticket is referring to. Since you seem to have addressed the issue yourself I am closing it.

**Comment by brunano21** [comment]
Hi @csnover, I was referring to this helper, into dnd branch, https://github.com/theintern/leadfoot/blob/dnd/helpers/DragAndDrop.js
