### ISSUE TITLE
support Edge

### ISSUE THREAD

**Issue by wkeese** [theintern/leadfoot#67]
Intern 3 and Intern 2 geezer should support Ege.

Currently Leadfoot (or at least Intern) apparently hangs during the feature testing.

I set up my tests as follows:

On main machine running Intern:

* Add "MicrosoftEdge" to the intern.local.js `environments` array.
* Start selenium as hub: `$ java -jar selenium-server-standalone-2.48.2.jar -role hub`

On VM running Windows 10:

* Install Java
* Install Selenium
* Install Microsoft Edge WebDriver from https://www.microsoft.com/en-us/download/details.aspx?id=48212
* (optional) Install Itunes so the the `.local` domain works.
* Start selenium as a node: `C:\ProgramData\Oracle\Java\javapath\java.exe -Dwebdriver.edge.driver="MicrosoftWebDriver.exe" -jar selenium-server-standalone-2.48.2.jar -role node -browser browserName="MicrosoftEdge" -hub http://mac.local:4444/grid/register`

Then, try running any test.

**Comment by kitsonk** [comment]
Strange, I have been using Intern 3 against BrowserStack Edge for a while now [without issue](https://travis-ci.org/dojo/parser#L166).

**Comment by wkeese** [comment]
Well, that's good.  I couldn't get it to work locally or on SauceLabs though.  You can see result in https://saucelabs.com/tests/0427bc3a674d4ed491fafba1dc999a13 where (it looks like) it's hanging testing if `transform` works.

**Comment by sholladay** [comment]
I also experience this on BrowserStack.

### Test
````javascript
define(
    [
        'intern!tdd',
        'intern/chai!assert'
    ],
    function (tdd, assert) {
        suite('simple', function () {
            console.log('this too shall pass');
        });
    }
);
````

### Intern config
````javascript
define(function () {
    'use strict';
    return {
        capabilities : {
            project : 'hanging-intern'
        },
        environments : [
            { os: 'Windows', os_version: '10',       browser: 'edge',    browser_version: '12.0' }
        ],
        tunnel : 'BrowserStackTunnel',
        suites : [
            'test/unit/foo'
        ]
    };
});
````

### Stack trace
Note: It hangs at `Tunnel started` for **4.5 minutes**. Only then does the stack trace appear. Interestingly, `Created session ...` does not appear until just before it fails.
````bash
sholladay$ node node_modules/.bin/intern-runner config=config/intern-cloud
Listening on 0.0.0.0:9000
Tunnel started
‣ Created session Any browser on any platform (3250b04e9566c6668cc6020fc240852bc725cd46)
Suite Any browser on any platform - unit tests FAILED
UnknownError: [POST http://(redacted)@hub.browserstack.com:4444/wd/hub/session/3250b04e9566c6668cc6020fc240852bc725cd46/url / {"url":"http://localhost:9000/__intern/client.html?config=config%2Fintern-cloud&basePath=%2F&initialBaseUrl=%2F&reporters=%7B%22id%22%3A%22WebDriver%22%7D&rootSuiteName=Any%20browser%20on%20any%20platform%20-%20unit%20tests&sessionId=3250b04e9566c6668cc6020fc240852bc725cd46"}] Session not started or terminated
  at runRequest  <node_modules/leadfoot/Session.js:88:40>
  at <node_modules/leadfoot/Session.js:109:39>
  at new Promise  <node_modules/dojo/Promise.ts:411:3>
  at ProxiedSession._post  <node_modules/leadfoot/Session.js:63:10>
  at ProxiedSession.Session.get  <node_modules/leadfoot/Session.js:575:15>
  at <node_modules/intern/lib/ProxiedSession.js:86:25>
  at getFinalValue  <node_modules/dojo/Promise.ts:462:21>
  at <node_modules/dojo/Promise.ts:482:10>
  at <node_modules/dojo/Promise.ts:393:15>
  at runCallbacks  <node_modules/dojo/Promise.ts:11:11>
  at Command.target.(anonymous function) [as get]  <node_modules/leadfoot/Command.js:610:11>
  at ClientSuite.lang.mixin.run  <node_modules/intern/lib/ClientSuite.js:149:6>
  at runWithCatch  <node_modules/intern/lib/Suite.js:314:21>
  at next  <node_modules/intern/lib/Suite.js:322:18>
  at <node_modules/intern/lib/Suite.js:345:6>
  at new Promise  <node_modules/intern/node_modules/dojo/Promise.ts:411:3>
  at runTests  <node_modules/intern/lib/Suite.js:278:12>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at runCallbacks  <node_modules/intern/node_modules/dojo/Promise.ts:11:11>
  at <node_modules/intern/node_modules/dojo/Promise.ts:317:4>
No unit test coverage for Any browser on any platform
Any browser on any platform: 0/0 tests failed; fatal error occurred


TOTAL: tested 1 platforms, 0/0 tests failed; fatal error occurred
Error: One or more suite errors occurred during testing
  at <node_modules/intern/lib/executors/Executor.js:301:13>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at runCallbacks  <node_modules/intern/node_modules/dojo/Promise.ts:11:11>
  at <node_modules/intern/node_modules/dojo/Promise.ts:317:4>
  at run  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
  at <node_modules/intern/node_modules/dojo/nextTick.ts:44:3>
  at nextTickCallbackWith0Args  <node.js:456:9>
  at process._tickCallback  <node.js:385:13>
````

**Comment by jason0x43** [comment]
Edge support has been significantly improved since this ticket was opened. Most features are working properly in the current version (1.6.10) with the most recent MicrosoftWebDriver and Edge version (143666), and the next release of Leadfoot (1.6.11) flags or works around the remaining...Edge-cases (yes, I said that). Note that there are still some features that are broken upstream, like file uploads. I'm going to close this for now, and we can re-open it or start something else if new Edge-specific issues come up.
