### ISSUE TITLE
Error due to implicit file upload functionality of type()

### ISSUE THREAD

**Issue by d-werner** [theintern/leadfoot#77]
Hi guys,

I experience this error, using type() for a standard text input field:

```
Error: EISDIR: illegal operation on a directory, read
at Error  <native>
at Object.fs.readSync  <fs.js:652:19>
at Object.fs.readFileSync  <fs.js:473:24>
```

This happens because ...
1.  the passed input text value accidentally coincides with a directory name in the current working directory 
2.  the session capability for `remoteFiles` is enabled.

The code is also part of the latest version 1.7.0-pre (s. https://github.com/theintern/leadfoot/blob/master/Element.js#L196-L199):

```
if (this.session.capabilities.remoteFiles) {
var filename = value.join('');

if (fs.existsSync(filename)) {
var self = this;
return this.session._uploadFile(filename).then(function (uploadedFilename) {
return self._post('value', {
value: [uploadedFilename]
}).then(noop);
});
}
}
```

Perhaps the API should be more explicit in regards of file upload field typing. 
Apart from that, thanks for your work on intern.js and leadfoot! :-)

**Comment by jason0x43** [comment]
Hmmm...good point. [The docs](https://theintern.github.io/leadfoot/module-leadfoot_Command.html#type) do currently point out that you should use `Session#pressKeys` instead of `Element#type` if you don't want to upload files, but that could be made clearer. Possibly Element.type could accept objects as well as strings so we could more explicitly indicate that a file is being passed. I'll have to think about that one.

**Comment by d-werner** [comment]
I see! The docs are quite misleading then. ;-)

`Types into the element. This method works the same as the leadfoot/Session#pressKeys method except that any modifier keys are automatically released at the end of the command. This method should be used instead of leadfoot/Session#pressKeys to type filenames into file upload fields.`

It does not explicitly say that `Element#type` it is restricted to file uploads. On the contrary, the text indicates that it is just an extended version of `Session#pressKeys` with file upload and different modifier keys handling.
And this impression gets even encouraged by the function's name.

**Comment by jason0x43** [comment]
`Element#type` isn't restricted to file uploads, and is the standard way to type values into inputs, but it will implicitly to do do some file upload-related things if you happen to type a string that is also a local file path. This is a bit surprising, but it's not entirely inconsistent with how the WebDriver standard handles inputs. Typing into a file input will cause file-related activity (e.g., opening a file dialog on the target), while typing into a text input will simply enter text.

**Comment by jason0x43** [comment]
Closing this since the current docs point out that typing a path using `type` will lead to file uploads.
