### ISSUE TITLE
BrowserStack Feature Detection Issue on Safari

### ISSUE THREAD

**Issue by kitsonk** [theintern/leadfoot#79]
Using the version of Leadfoot that is required by Intern 3.2.0 and the following configuration:

```js
{ browser: 'Safari', 'os': 'OS X', 'os_version': 'El Capitan' }
```

The session hangs during feature detection and I get the following error reported:

```
Created session Any browser on any platform (a59627523b76074645aee771b7f310989ae9b86c)
>> Suite Any browser on any platform - unit tests FAILED
ScriptTimeout: [POST https://(redacted)@hub.browserstack.com:443/wd/hub/session/a59627523b76074645aee771b7f310989ae9b86c/execute / {"script":"return (function getCoverageData(coverageVariable) {\n\t\tvar coverageData = (function () { return this; })()[coverageVariable];\n\t\treturn coverageData && JSON.stringify(coverageData);\n\t}).apply(this, arguments);","args":["__internCoverage"]}] Timed out awaiting response to command "executeScript" after 30001 ms (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 30.01 seconds
```

Here is [an example](https://www.browserstack.com/automate/builds/1899a5b01c40f3dfbd8e6195f511c5a7b911b213/sessions/a59627523b76074645aee771b7f310989ae9b86c#automate_button).

**Comment by jason0x43** [comment]
Hmmm...the link to that example case isn't working for me (BS says it doesn't exist). What project were you running the tests with?

In any case, I agree that there seems to be an issue with Safari. However, feature detection seems to be working fine in my test runs on Sauce Labs or Browserstack. The issue I see is that the Safari sessions aren't completing. The tests appear to complete in the interactive view, but results aren't making it back to the browser.

**Comment by kitsonk** [comment]
Again, apologies for not realising it wasn't shareable:

It is [dojo-compose](https://github.com/dojo/compose/tree/feature-update-intern) and terminates with a blank screen and this in the BrowserStack logs:

`Run JavaScript return (function getCoverageData(coverageVariable) { var coverageData = (function () { return this; })()[coverageVariable]; return coverageData && JSON.stringify(coverageData); }).apply(this, arguments);+`
`⇒Timed out awaiting response to command "executeScript" after 30001 ms (WARNING: The server did not provide any stacktrace information) Command duration or timeout: 30.01 seconds Build info: version: '2.45.0', revision: '5017cb8', time: '2015-02-26 23:59:50' System info: host: 'mac-5-255-93-93.browserstack.com', ip: '5.255.93.93', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11', java.version: '1.8.0_65' Driver info: org.openqa.selenium.safari.SafariDriver Capabilities [{browserName=safari, takesScreenshot=true, javascriptEnabled=true, version=9.0, cssSelectorsEnabled=true, platform=MAC, secureSsl=true}] Session ID: null`

**Comment by jason0x43** [comment]
Does this happen with 1.6.8 (Intern 3.2.1)? I could never reproduce this, but I made a few stability improvements in 1.6.8, including one additional defect flag for Safari.

**Comment by kitsonk** [comment]
Doesn't occur any longer, not if it was a transitory issue on BS or what.
