### ISSUE TITLE
Workaround request: Safari WebDriver does not always trigger change events

### ISSUE THREAD

**Issue by mambocab** [theintern/leadfoot#8]
As described [here](https://code.google.com/p/selenium/issues/detail?id&#61;4061), the Safari WebDriver does not cause a change event when leaving an input field after the text in the field has changed. This seems to be a limitation of the Safari WebDriver's JavaScript implementation, as described [here](https://code.google.com/p/selenium/issues/detail?id&#61;5403).

Here's an Intern test suite that fails because of this limitation:

```js
define([
'intern!object',
'intern/chai!assert',
], function (registerSuite, assert) {
appUrl = 'http://mithril-test.cos.io/basic/';
registerSuite({
name: 'demonstrate WebDriver problem',

'typing, then clicking submit adds todo item': function() {
return this.remote
.get(appUrl)
.findByLinkText('todo').click().end()
.findByTagName('input').click().type('three').end()
.findById('content').findByTagName('button').click().end()
.findById('content').findAllByTagName('li').getVisibleText()
.then(function(data) {
assert.deepEqual(data, ['one', 'two', 'three'], 'new item added to list');
});
},
});
});
```

This succeeds when performing the tasks manually in Safari. It also acts as expected in Chrome, both when performed manually and through the WebDriver.

Is this a limitation that LeadFoot can work around? I'm willing to put some time in on this as well if you can direct me to the part the codebase where I might implement a workaround.

**Comment by jason0x43** [comment]
Closing this since SafariDriver is no longer the primary way to access Safari
