### ISSUE TITLE
TypeError: Cannot read property 'supportsKeysCommand' of undefined

### ISSUE THREAD

**Issue by Ravoltz** [theintern/leadfoot#81]
This is caused due to a typo at https://github.com/theintern/leadfoot/blob/6bc6ac63a73ca51883241f38023889c0dea57cbf/Session.js#L1316

'capabilites' should be 'capabilities'

**Comment by jason0x43** [comment]
Fixed in 1.6.10

**Comment by Ravoltz** [comment]
Thanks. Appreciate the quick fix!
