### ISSUE TITLE
Leadfoot crashes when typing a slash ('/') into an input field

### ISSUE THREAD

**Issue by Kiechlus** [theintern/leadfoot#85]
OS: Ubuntu 16.04
Browser: Chrome
Node: v4.2.6

```
Type slash into an input field': function () {
return this.remote.get('http://www.google.de').end().findById('lst-ib').type('/')
}
```

```
× chrome on any platform - Localhost throwing error (0.733s)
Error: EISDIR: illegal operation on a directory, read
at Error  <native>
at Object.fs.readSync  <fs.js:603:19>
at Object.fs.readFileSync  <fs.js:438:24>
at <node_modules/intern/node_modules/leadfoot/Session.js:1933:21>
```

**Comment by jason0x43** [comment]
This is probably related to #77

**Comment by Kiechlus** [comment]
The problem is that we are somewhere down in the promise chain where we only have elements and not command objects. Element does not have the `pressKeys` function.

As a workaround we used:
```
injectContext(element) {
  return this.remote
    .then((p, setContext)=> setContext(element));
}
```
`...
return injectContext(element).click().pressKeys(value);`

**Comment by jason0x43** [comment]
Closing as Element now checks whether the potential file is actually a file before trying to upload it.
