### ISSUE TITLE
Press keys doesn't seem to work on Gecko driver

### ISSUE THREAD

**Issue by Acanthostega** [theintern/leadfoot#91]
Hello,

I'm trying to run some tests with the latest selenium standalone version (3.0.0-beta3) on a web application I've developped. All the tests work fine on Chrome, (even on IE, although quite slowly ;) ) but when I try to run them on Firefox (yes, I did set "marionette" to true) they fail. 
The returned error, sent by the driver, is : 
`TypeError: event.initKeyboardEvent is not a function`

After some research I found in the Leadfoot code the mentionned function and did some internet research, and it seems that particular function wasn't developped in the Gecko driver but instead the function "initKeyEvent" was. 

So, is there a way to workaround this issue or does it needs a fix ? or maybe is it already fixed but I've got the wrong version ?

Nobody seems to have this problem so I'm wondering if maybe I'm doing something wrong.

**Comment by jason0x43** [comment]
It's possible Firefox may have recently removed support for `initKeyboardEvent`. Leadfoot will need to switch to the KeyboardEvent constructor (where available).

Another question is why that function is even being called. It should only come into play when simulated (rather than native) key events are in use.

**Comment by Acanthostega** [comment]
Do you need more informations on how we are making our tests? Tests are done with intern, with a selenium standalone server launched with the 0.10.0 version of the geckodriver with recent versions of Firefox (>=48) and marionette activated, on Windows (not tested yet on Linux).

**Comment by Acanthostega** [comment]
Same thing on Linux and the latest selenium server.

**Comment by jason0x43** [comment]
This was resolved in Leadfoot 1.7.0
