### ISSUE TITLE
selecting elements by id

### ISSUE THREAD

**Issue by rodneyrehm** [theintern/leadfoot#92]
It is my understanding that the following calls should produce the same result:

```js
.findById('gustav');
.findByCssSelector('#gustav');
.execute('return document.getElementById("gustav")');
```

I have tests where `.findById()` fails in IE10, but the `.execute()` variant works fine. The `.execute()` approach fails a few other tests in other browsers, though. The one, that currently runs all tests in all browsers, is `.findByCssSelector()`.

Is this a known issue? How would I go about debugging this?

**Comment by jason0x43** [comment]
What error(s) are you seeing? Is it possible the page isn't fully loaded when the find commands are being run? If that's possible, you could do a `setFindTimeout`. Some browsers/drivers default to a 0 ms timeout.

**Comment by rodneyrehm** [comment]
> What error(s) are you seeing? 

```
CancelError: Timeout reached on IE10 on WIN - fix/pointer-focus-children - for all elements - should handle child of focusable flexbox container
  at null._onTimeout  <node_modules/intern/lib/Test.js:134:20>
  at Timer.listOnTimeout  <timers.js:89:15>
  at Command.then  <node_modules/intern/node_modules/leadfoot/Command.js:542:10>
  at Command.finally  <node_modules/intern/node_modules/leadfoot/Command.js:566:15>
  at <node_modules/intern/lib/Test.js:209:37>
  at Promise.cancel  <node_modules/intern/browser_modules/dojo/Promise.ts:343:37>
  at null._onTimeout  <node_modules/intern/lib/Test.js:136:21>
  at Timer.listOnTimeout  <timers.js:89:15>
```

The element definitely exists. The ID exists exactly once. The document is fully loaded.


> Is it possible the page isn't fully loaded when the find commands are being run?

no. I'm polling a global variable that gets set once the JS is fully initialized. The first test of the suite - also using `.findById()` or `.findByCssSelector()` passes just fine.


> If that's possible, you could do a `setFindTimeout`

already set to 120s

---

I'm not sure what's happening here. The first few runs with `.findByCssSelector()` worked fine, now they're failing too.

**Comment by LingSpb** [comment]
I seem to have a similar issue. I feel it has something wrong with the Promises/context, but I haven't had time to dig into yet.

**Comment by jason0x43** [comment]
Note: `.execute('return document.getElementById("#gustav")');` should use `"gustav"`, not `"#gustav"`.

In any case, though, a CancelError means that the test didn't finish in the time allotted, not necessarily that the element wasn't found (although it could be that the test timed out because it was still waiting for the element to be found). Try increasing the test timeout.

**Comment by rodneyrehm** [comment]
> … should use "gustav", not "#gustav".

of course, typo in this issue.


> In any case, though, a CancelError means that the test didn't finish in the time allotted, …

I've traced the problem to `findById()` by adding `.then(logStep, logError)` after each leadfoot command. the last output I get is *before* `findById()`. The first "error" I get logged is the promise returned by `findById()`.


> Try increasing the test timeout.

I think at two minutes for all timeouts we've reached the point where simply "increasing the timeouts" doesn't make sense anymore…

**Comment by jason0x43** [comment]
> I think at two minutes for all timeouts we've reached the point where simply "increasing the timeouts" doesn't make sense anymore…

Ah, from your earlier comment I had assumed you were only setting the find timeout, not the async test timeout as well. Note that these are different things. There is a timeout for async tests that defaults to 30s (I believe), and also 3 different timeouts for Leadfoot actions (the 'find' one being the interesting one here). Setting one of these has no effect on the others. The overall test timeout (set via `this.timeout = x` or `this.async(x)` in a test) needs to be larger than the sum of all the times required by the actions in the test. So if, for example, the test has 3 finds that take 2 minutes each, the test timeout needs to be at least 6 minutes.

**Comment by rodneyrehm** [comment]
I doubled the test's timeout to 240s, the other three remain at 120s. Now I'm getting the following error

```
× IE10 on WIN - fix/pointer-focus-children - for all elements - should handle child of focusable flexbox container (120.921s)
SyntaxError: Unexpected end of input
  at runRequest  <node_modules/intern/node_modules/leadfoot/Session.js:88:40>
  at <node_modules/intern/node_modules/leadfoot/Session.js:109:39>
  at new Promise  <node_modules/intern/node_modules/dojo/Promise.ts:411:3>
  at ProxiedSession._post  <node_modules/intern/node_modules/leadfoot/Session.js:63:10>
  at Element._post  <node_modules/intern/node_modules/leadfoot/Element.js:23:31>
  at Element.click  <node_modules/intern/node_modules/leadfoot/Element.js:163:15>
  at Command.<anonymous>  <node_modules/intern/node_modules/leadfoot/Command.js:680:19>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at run  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
  at <node_modules/intern/node_modules/dojo/nextTick.ts:44:3>
  at Command.target.(anonymous function) [as click]  <node_modules/intern/node_modules/leadfoot/Command.js:674:11>
  at Command.<anonymous>  <test/helper/leadfoot-commands.js:71:12>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at run  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
  at <node_modules/intern/node_modules/dojo/nextTick.ts:44:3>
  at nextTickCallbackWith0Args  <node.js:420:9>
  at process._tickCallback  <node.js:349:13>
  at Command.focusById  <test/helper/leadfoot-commands.js:66:12>
  at Test.test  <test/functional/fix.pointer-focus-children.test.js:15:12>
  at <node_modules/intern/lib/Test.js:184:24>
  at <node_modules/intern/browser_modules/dojo/Promise.ts:393:15>
  at runCallbacks  <node_modules/intern/browser_modules/dojo/Promise.ts:11:11>
  at <node_modules/intern/browser_modules/dojo/Promise.ts:317:4>
  at run  <node_modules/intern/browser_modules/dojo/Promise.ts:237:7>
  at <node_modules/intern/browser_modules/dojo/nextTick.ts:44:3>
  at nextTickCallbackWith0Args  <node.js:420:9>
  at process._tickCallback  <node.js:349:13>
```

**Comment by rodneyrehm** [comment]
I'm an idiot! It turns out this is a problem with IE driver and nativeEvents clicking. I've [seen this before](https://gist.github.com/rodneyrehm/23df2ae750ca5bac96f7ad93ffcf69bd) in another test and reported it to BrowserStack support, but they couldn't figure it out either. I guess it's just another test I'll have to skip…
