### ISSUE TITLE
.getSpecAttribute('innerHTML') always returns null in FF48+

### ISSUE THREAD

**Issue by KikoRamos** [theintern/leadfoot#94]
#### Issue
I had been running some tests that used `.getSpecAttribute('innerHTML')` to get the text of a hidden element. Recently, these tests started to fail once updated to run on FF48+. Upon investigation, it appears that the aforementioned code now only returns `null` regardless of element visibility.

#### Environment
os: OS X El Capitan
node: v6.2.0
browser: Firefox 48+

#### Code example
【 code js 】
command
 .findByCssSelector(selector)
 .getSpecAttribute('innerHTML')
 .then(function (text) {
 console.log(text);
 });
【 end code 】

**Comment by LingSpb** [comment]
Why don't you use `.getProperty('innerHTML')`?
Read more about `getSpecAttribute` [here](https://theintern.github.io/leadfoot/module-leadfoot_Command.html#getSpecAttribute)

**Comment by jason0x43** [comment]
Closing this as `getSpecAttribute` does work with current Firefox (72) and geckodriver (0.26).
