### ISSUE TITLE
Migrate Leadfoot to TypeScript

### ISSUE THREAD

**Issue by morrinene** [theintern/leadfoot#96]
As part of the ES6/TS refactor, we are migrating Leadfoot to TypeScript.  This issue will cover the conversion and test updates needed.

Be sure to take into consideration work done for the Intern Migration: theintern/intern#674

**Comment by nicknisi** [comment]
I have removed the CancelablePromise class from the project, and switched everything to use Task instead after discussing with @jason0x43 the necessity of a cancelled Promise to throw a `CancelError`. The tests run and pass, but the unit tests are throwing an error when run along with the functional tests.

**Comment by jason0x43** [comment]
The refactor is now in master (f9c492a)
